POST  http://localhost:3000/api/v1/schema
Content-Type: application/json

{
    "dialect": "postgres", 
    "host": "localhost", 
    "user": "postgres", 
    "password": "postgres" , 
    "database": "postgres", 
    "uri": "",
    "port": 5234
}